#34,#46 added datastore methods for plotting to read refreshed data
mheidebr/Electric-Car-Racing pull request #47
Opened 2021-02-08 19:48 UTC by rdriven

Added a new get_new_data_values method in datastore to get a dictionary containing all the computed lists as well as the new refresh_index which was updated by SimulationThread which tells the consumer (MainWindow) the index where to start refreshing from. 

Tested on currently included track to see that the plots updated after SimulationThread walked back the calculations to meet the velocity constraints envelope.

2021-02-09 03:03 UTC, mheidebr requested changes
Just needs some little clean up and its good to go! I tested on my machine and it worked well. I couldn't get ptvsd debugging to work but I think thats something that is only an issue on my machine and we don't need to address in the pr

2021-02-09 03:03 UTC, mheidebr commented on datastore.py
> +
white space

2021-02-09 03:03 UTC, mheidebr commented on visualization.py
> +        # self.simulationThread.simulationThreadWalkBackCompleteSignal.connect(self.signalWalkBackComplete)
commented code

2021-02-09 03:03 UTC, mheidebr commented on visualization.py
> +
Unused function?

2021-02-09 20:12 UTC, rdriven commented on datastore.py
> +
Meh... ok, I'll change it by deleting the line and some others in the file and commit There's a lot of time that could be spent on cleaning up lint issues. Are we going to be consistent and require lint-free submissions for all files from here on out? I'm ok with that.

2021-02-09 20:17 UTC, rdriven commented on visualization.py
> +        # self.simulationThread.simulationThreadWalkBackCompleteSignal.connect(self.signalWalkBackComplete)
Removed comment line and the heretofore commented out the associated (deprecated) walk back complete signal handler. Will be put in the next immanent commit.

2021-02-09 20:19 UTC, rdriven commented on visualization.py
> +
This method is still used. When the simulation thread changes states (e.g. to "Calculating") this method is called via by the Slot/Signal mechanism to update the GUI textboxStatus so the user knows what's going on.

2021-02-10 18:51 UTC, rdriven commented
Addressed the merge conflict in visualization.py with commit d7478e5. Tested that version in VS Code and it runs w/o errors. Then tested via Linux command line "python3 main.py" which yielded execution errors. This is because of inclusion of the ptvsd multithread debugging library and calls to set breakpoints and is compatible with the VS Code execution environment, but it causes errors when running via in stand alone mode. Commented out the harmful 2 lines, successfully tested in both environments then committed (33394ff) changes. Should be good to go!

2021-02-12 00:08 UTC, rdriven commented on datastore.py
> +
Changes made.

2021-02-12 04:34 UTC, mheidebr approved these changes

2021-02-12 04:36 UTC, merged